
class EnumValues<T> {
    Map<String, T> map;
    Map<T, String> reverseMap;

    EnumValues(this.map);

    Map<T, String> get reverse {
        if (reverseMap == null) {
            reverseMap = map.map((k, v) => new MapEntry(v, k));
        }
        return reverseMap;
    }
}


enum ImageTags { ALL_IMAGES, ALL_IMAGES_VIRTUAL_REALITY, ALL_IMAGES_BOX_ART, ALL_IMAGES_COVER_ART }

final imageTagsValues = new EnumValues({
    "All Images": ImageTags.ALL_IMAGES,
    "All Images,Box Art": ImageTags.ALL_IMAGES_BOX_ART,
    "All Images,Cover Art": ImageTags.ALL_IMAGES_COVER_ART,
    "All Images,Virtual Reality": ImageTags.ALL_IMAGES_VIRTUAL_REALITY
});

enum AbbreviationFilter { PC, XONE, PS4, NSW, IPHN, ANDR, MAC, LIN, 
IPAD, ARC, PSNV, THE_3_DS, VITA, APTV, XBOX , N64, PS1, GCN, PS2, WII, PS3, WIIU}

final abbreviationFilterValues = new EnumValues({
    "ANDR": AbbreviationFilter.ANDR,
    "APTV": AbbreviationFilter.APTV,
    "ARC": AbbreviationFilter.ARC,
    "IPAD": AbbreviationFilter.IPAD,
    "IPHN": AbbreviationFilter.IPHN,
    "LIN": AbbreviationFilter.LIN,
    "MAC": AbbreviationFilter.MAC,
    "NSW": AbbreviationFilter.NSW,
    "PC": AbbreviationFilter.PC,
    "PS4": AbbreviationFilter.PS4,
    "PSNV": AbbreviationFilter.PSNV,
    "3DS": AbbreviationFilter.THE_3_DS,
    "VITA": AbbreviationFilter.VITA,
    "XBOX": AbbreviationFilter.XBOX,
    "XONE": AbbreviationFilter.XONE,
    "N64": AbbreviationFilter.N64,
    "PS1": AbbreviationFilter.PS1,
    "GCN": AbbreviationFilter.GCN,
    "PS2": AbbreviationFilter.PS2,
    "WII": AbbreviationFilter.WII,
    "PS3": AbbreviationFilter.PS3,
    "WIIU": AbbreviationFilter.WIIU,
});

// enum Abbreviation { PC, XONE, PS4, NSW}
enum Abbreviation { AMI,GB,GBA,GG,GEN,LYNX,SMS,SNES,CPC,APL2,AST,C64,MSX,SPEC,MAC,PSP,PS2,X360,NES,PS1,GCN,A800,NEO,THE_3DO,CDI,JAG,SCD,VC20,THE_32X,XBOX,NGE,PS3,Wii,DC,A2GS,CD32,SAT,N64,CVIS,TI99,INTV,DS,TGCD,WSC,TG16,GBC,C128,NGCD,ODY2,DRAG,CBM,TRS8,ZOD,WSW,CHANF,COCO,IPOD,ODY,PCFX,VECT,GCOM,GIZ,VBOY,NGP,NGPC,VSML,PIN,ARC,NUON,XBGS,WSHP,PS3N,LEAP,MVIS,FDS,LACT,AVIS,PC,X68K,IPHN,A2K1,AQUA,THE_64DD,PIPN,RZON,HSCN,GWAV,DSI,HALC,FMT,PC88,BBCM,PLATO,PC98,X1,FM7,PSPN,THE_3DS,PICO,SGFX,BAST,IPAD,ZBO,ANDR,WP,ACRN,LOOP,PDIA,MZ,VITA,RCA2,XAVX,GP32,PMIN,CASV,SCV,DUCK,THE_3DSE,WiiU,BROW,SG1K,CDTV,PSNV,DIDJ,XONE,PS4,SVIS,AMAX,PV1K,C16,ACAN,LIN,VIS,OUYA,FIRE,N3DS,NSW,HGM,APTV,SMC7,COUP,VMIV,TF1,TUT,GMT,MBEE,VSOC,ABC,JCD,ALXA,ML1,BNA,STAD}

final abbreviationValues = new EnumValues({
    "AMI" : Abbreviation.AMI,
    "GB" : Abbreviation.GB,
    "GBA" : Abbreviation.GBA,
    "GG" : Abbreviation.GG,
    "GEN" : Abbreviation.GEN,
    "LYNX" : Abbreviation.LYNX,
    "SMS" : Abbreviation.SMS,
    "SNES" : Abbreviation.SNES,
    "CPC" : Abbreviation.CPC,
    "APL2" : Abbreviation.APL2,
    "AST" : Abbreviation.AST,
    "C64" : Abbreviation.C64,
    "MSX" : Abbreviation.MSX,
    "SPEC" : Abbreviation.SPEC,
    "MAC" : Abbreviation.MAC,
    "PSP" : Abbreviation.PSP,
    "PS2" : Abbreviation.PS2,
    "X360" : Abbreviation.X360,
    "NES" : Abbreviation.NES,
    "PS1" : Abbreviation.PS1,
    "GCN" : Abbreviation.GCN,
    "A800" : Abbreviation.A800,
    "NEO" : Abbreviation.NEO,
    "3DO" : Abbreviation.THE_3DO,
    "CDI" : Abbreviation.CDI,
    "JAG" : Abbreviation.JAG,
    "SCD" : Abbreviation.SCD,
    "VC20" : Abbreviation.VC20,
    "32X" : Abbreviation.THE_32X,
    "XBOX" : Abbreviation.XBOX,
    "NGE" : Abbreviation.NGE,
    "PS3" : Abbreviation.PS3,
    "Wii" : Abbreviation.Wii,
    "DC" : Abbreviation.DC,
    "A2GS" : Abbreviation.A2GS,
    "CD32" : Abbreviation.CD32,
    "SAT" : Abbreviation.SAT,
    "N64" : Abbreviation.N64,
    "CVIS" : Abbreviation.CVIS,
    "TI99" : Abbreviation.TI99,
    "INTV" : Abbreviation.INTV,
    "DS" : Abbreviation.DS,
    "TGCD" : Abbreviation.TGCD,
    "WSC" : Abbreviation.WSC,
    "TG16" : Abbreviation.TG16,
    "GBC" : Abbreviation.GBC,
    "C128" : Abbreviation.C128,
    "NGCD" : Abbreviation.NGCD,
    "ODY2" : Abbreviation.ODY2,
    "DRAG" : Abbreviation.DRAG,
    "CBM" : Abbreviation.CBM,
    "TRS8" : Abbreviation.TRS8,
    "ZOD" : Abbreviation.ZOD,
    "WSW" : Abbreviation.WSW,
    "CHANF" : Abbreviation.CHANF,
    "COCO" : Abbreviation.COCO,
    "IPOD" : Abbreviation.IPOD,
    "ODY" : Abbreviation.ODY,
    "PCFX" : Abbreviation.PCFX,
    "VECT" : Abbreviation.VECT,
    "GCOM" : Abbreviation.GCOM,
    "GIZ" : Abbreviation.GIZ,
    "VBOY" : Abbreviation.VBOY,
    "NGP" : Abbreviation.NGP,
    "NGPC" : Abbreviation.NGPC,
    "VSML" : Abbreviation.VSML,
    "PIN" : Abbreviation.PIN,
    "ARC" : Abbreviation.ARC,
    "NUON" : Abbreviation.NUON,
    "XBGS" : Abbreviation.XBGS,
    "WSHP" : Abbreviation.WSHP,
    "PS3N" : Abbreviation.PS3N,
    "LEAP" : Abbreviation.LEAP,
    "MVIS" : Abbreviation.MVIS,
    "FDS" : Abbreviation.FDS,
    "LACT" : Abbreviation.LACT,
    "AVIS" : Abbreviation.AVIS,
    "PC" : Abbreviation.PC,
    "X68K" : Abbreviation.X68K,
    "IPHN" : Abbreviation.IPHN,
    "A2K1" : Abbreviation.A2K1,
    "AQUA" : Abbreviation.AQUA,
    "64DD" : Abbreviation.THE_64DD,
    "PIPN" : Abbreviation.PIPN,
    "RZON" : Abbreviation.RZON,
    "HSCN" : Abbreviation.HSCN,
    "GWAV" : Abbreviation.GWAV,
    "DSI" : Abbreviation.DSI,
    "HALC" : Abbreviation.HALC,
    "FMT" : Abbreviation.FMT,
    "PC88" : Abbreviation.PC88,
    "BBCM" : Abbreviation.BBCM,
    "PLATO" : Abbreviation.PLATO,
    "PC98" : Abbreviation.PC98,
    "X1" : Abbreviation.X1,
    "FM7" : Abbreviation.FM7,
    "PSPN" : Abbreviation.PSPN,
    "3DS" : Abbreviation.THE_3DS,
    "PICO" : Abbreviation.PICO,
    "SGFX" : Abbreviation.SGFX,
    "BAST" : Abbreviation.BAST,
    "IPAD" : Abbreviation.IPAD,
    "ZBO" : Abbreviation.ZBO,
    "ANDR" : Abbreviation.ANDR,
    "WP" : Abbreviation.WP,
    "ACRN" : Abbreviation.ACRN,
    "LOOP" : Abbreviation.LOOP,
    "PDIA" : Abbreviation.PDIA,
    "MZ" : Abbreviation.MZ,
    "VITA" : Abbreviation.VITA,
    "RCA2" : Abbreviation.RCA2,
    "XAVX" : Abbreviation.XAVX,
    "GP32" : Abbreviation.GP32,
    "PMIN" : Abbreviation.PMIN,
    "CASV" : Abbreviation.CASV,
    "SCV" : Abbreviation.SCV,
    "DUCK" : Abbreviation.DUCK,
    "3DSE" : Abbreviation.THE_3DSE,
    "WiiU" : Abbreviation.WiiU,
    "BROW" : Abbreviation.BROW,
    "SG1K" : Abbreviation.SG1K,
    "CDTV" : Abbreviation.CDTV,
    "PSNV" : Abbreviation.PSNV,
    "DIDJ" : Abbreviation.DIDJ,
    "XONE" : Abbreviation.XONE,
    "PS4" : Abbreviation.PS4,
    "SVIS" : Abbreviation.SVIS,
    "AMAX" : Abbreviation.AMAX,
    "PV1K" : Abbreviation.PV1K,
    "C16" : Abbreviation.C16,
    "ACAN" : Abbreviation.ACAN,
    "LIN" : Abbreviation.LIN,
    "VIS" : Abbreviation.VIS,
    "OUYA" : Abbreviation.OUYA,
    "FIRE" : Abbreviation.FIRE,
    "N3DS" : Abbreviation.N3DS,
    "NSW" : Abbreviation.NSW,
    "HGM" : Abbreviation.HGM,
    "APTV" : Abbreviation.APTV,
    "SMC7" : Abbreviation.SMC7,
    "COUP" : Abbreviation.COUP,
    "VMIV" : Abbreviation.VMIV,
    "TF1" : Abbreviation.TF1,
    "TUT" : Abbreviation.TUT,
    "GMT" : Abbreviation.GMT,
    "MBEE" : Abbreviation.MBEE,
    "VSOC" : Abbreviation.VSOC,
    "ABC" : Abbreviation.ABC,
    "JCD" : Abbreviation.JCD,
    "ALXA" : Abbreviation.ALXA,
    "ML1" : Abbreviation.ML1,
    "BNA" : Abbreviation.BNA,
    "STAD" : Abbreviation.STAD,
});


enum Name { AMIGA,GAME_BOY,GAME_BOY_ADVANCE,GAME_GEAR,GENESIS,ATARI_LYNX,SEGA_MASTER_SYSTEM,SUPER_NINTENDO_ENTERTAINMENT_SYSTEM,AMSTRAD_CPC,APPLE_II,ATARI_ST,COMMODORE_64,MSX,ZX_SPECTRUM,MAC,PLAYSTATION_PORTABLE,PLAYSTATION_2,XBOX_360,NINTENDO_ENTERTAINMENT_SYSTEM,PLAYSTATION,GAMECUBE,ATARI_8_BIT,NEO_GEO,THE_3DO,CD_I,JAGUAR,SEGA_CD,VIC_20,SEGA_32X,XBOX,N_GAGE,PLAYSTATION_3,WII,DREAMCAST,APPLE_IIGS,AMIGA_CD32,ATARI_2600,SATURN,NINTENDO_64,COLECOVISION,TI_99_4A,INTELLIVISION,NINTENDO_DS,TURBOGRAFX_CD,WONDERSWAN_COLOR,TURBOGRAFX_16,GAME_BOY_COLOR,COMMODORE_128,NEO_GEO_CD,ODYSSEY_2,DRAGON_32_64,COMMODORE_PET_CBM,TRS_80,ZODIAC,WONDERSWAN,CHANNEL_F,ATARI_5200,TRS_80_COCO,ATARI_7800,IPOD,ODYSSEY,PC_FX,VECTREX,GAME_COM,GIZMONDO,VIRTUAL_BOY,NEO_GEO_POCKET,NEO_GEO_POCKET_COLOR,V_SMILE,PINBALL,ARCADE,NUON,XBOX_360_GAMES_STORE,WII_SHOP,PLAYSTATION_NETWORK_PS3,LEAPSTER,MICROVISION,FAMICOM_DISK_SYSTEM,PIONEER_LASERACTIVE,ADVENTURE_VISION,PC,SHARP_X68000,IPHONE,SATELLAVIEW,ARCADIA_2001,AQUARIUS,NINTENDO_64DD,PIPPIN,R_ZONE,HYPERSCAN,GAME_WAVE,DSIWARE,RDI_HALCYON,FM_TOWNS,NEC_PC_8801,BBC_MICRO,PLATO,NEC_PC_9801,SHARP_X1,FM_7,NEC_PC_6001,PLAYSTATION_NETWORK_PSP,NINTENDO_3DS,SEGA_PICO,SUPERGRAFX,BALLY_ASTROCADE,IPAD,ZEEBO,ANDROID,WINDOWS_PHONE,ACORN_ARCHIMEDES,CASIO_LOOPY,BANDAI_PLAYDIA,SHARP_MZ,PLAYSTATION_VITA,RCA_STUDIO_II,XAVIXPORT,GAMEPARK_32,POKEMON_MINI,EPOCH_CASSETTE_VISION,SUPER_CASSETTE_VISION,MEGA_DUCK,NINTENDO_3DS_ESHOP,WII_U,BROWSER,SEGA_SG_1000,COMMODORE_CDTV,PLAYSTATION_NETWORK_VITA,LEAPFROG_DIDJ,XBOX_ONE,PLAYSTATION_4,WATARA_SUPERVISION,ACTION_MAX,CASIO_PV_1000,COMMODORE_16,SUPER_A_CAN,LINUX,MEMOREX_MD_2500_VIS,OUYA,AMAZON_FIRE_TV,NEW_NINTENDO_3DS,NINTENDO_SWITCH,GAME_MASTER,APPLE_TV,SONY_SMC_777,SAM_COUPE,VIEW_MASTER_INTERACTIVE_VISION,FUZE_TOMAHAWK_F1,TOMY_TUTOR,GAMATE,MICROBEE,VTECH_SOCRATES,LUXOR_ABC80,JAGUAR_CD,AMAZON_ALEXA,MAGIC_LEAP_ONE,ADVANCED_PICO_BEENA,GOOGLE_STADIA,THE_NEXT_GEN_PLAYSTATION }

final nameValues = new EnumValues({
    "Amiga" : Name.AMIGA,
    "Game Boy" : Name.GAME_BOY,
    "Game Boy Advance" : Name.GAME_BOY_ADVANCE,
    "Game Gear" : Name.GAME_GEAR,
    "Genesis" : Name.GENESIS,
    "Atari Lynx" : Name.ATARI_LYNX,
    "Sega Master System" : Name.SEGA_MASTER_SYSTEM,
    "Super Nintendo Entertainment System" : Name.SUPER_NINTENDO_ENTERTAINMENT_SYSTEM,
    "Amstrad Cpc" : Name.AMSTRAD_CPC,
    "Apple Ii" : Name.APPLE_II,
    "Atari St" : Name.ATARI_ST,
    "Commodore 64" : Name.COMMODORE_64,
    "Msx" : Name.MSX,
    "Zx Spectrum" : Name.ZX_SPECTRUM,
    "Mac" : Name.MAC,
    "Playstation Portable" : Name.PLAYSTATION_PORTABLE,
    "Playstation 2" : Name.PLAYSTATION_2,
    "Xbox 360" : Name.XBOX_360,
    "Nintendo Entertainment System" : Name.NINTENDO_ENTERTAINMENT_SYSTEM,
    "Playstation" : Name.PLAYSTATION,
    "Gamecube" : Name.GAMECUBE,
    "Atari 8 Bit" : Name.ATARI_8_BIT,
    "Neo Geo" : Name.NEO_GEO,
    "3DO" : Name.THE_3DO,
    "Cd I" : Name.CD_I,
    "Jaguar" : Name.JAGUAR,
    "Sega Cd" : Name.SEGA_CD,
    "Vic 20" : Name.VIC_20,
    "Sega 32x" : Name.SEGA_32X,
    "Xbox" : Name.XBOX,
    "N Gage" : Name.N_GAGE,
    "Playstation 3" : Name.PLAYSTATION_3,
    "Wii" : Name.WII,
    "Dreamcast" : Name.DREAMCAST,
    "Apple Iigs" : Name.APPLE_IIGS,
    "Amiga Cd32" : Name.AMIGA_CD32,
    "Atari 2600" : Name.ATARI_2600,
    "Saturn" : Name.SATURN,
    "Nintendo 64" : Name.NINTENDO_64,
    "Colecovision" : Name.COLECOVISION,
    "Ti 99/4a" : Name.TI_99_4A,
    "Intellivision" : Name.INTELLIVISION,
    "Nintendo Ds" : Name.NINTENDO_DS,
    "Turbografx Cd" : Name.TURBOGRAFX_CD,
    "Wonderswan Color" : Name.WONDERSWAN_COLOR,
    "Turbografx 16" : Name.TURBOGRAFX_16,
    "Game Boy Color" : Name.GAME_BOY_COLOR,
    "Commodore 128" : Name.COMMODORE_128,
    "Neo Geo Cd" : Name.NEO_GEO_CD,
    "Odyssey 2" : Name.ODYSSEY_2,
    "Dragon 32/64" : Name.DRAGON_32_64,
    "Commodore Pet/cbm" : Name.COMMODORE_PET_CBM,
    "Trs 80" : Name.TRS_80,
    "Zodiac" : Name.ZODIAC,
    "Wonderswan" : Name.WONDERSWAN,
    "Channel F" : Name.CHANNEL_F,
    "Atari 5200" : Name.ATARI_5200,
    "Trs 80 Coco" : Name.TRS_80_COCO,
    "Atari 7800" : Name.ATARI_7800,
    "Ipod" : Name.IPOD,
    "Odyssey" : Name.ODYSSEY,
    "Pc Fx" : Name.PC_FX,
    "Vectrex" : Name.VECTREX,
    "Game.com" : Name.GAME_COM,
    "Gizmondo" : Name.GIZMONDO,
    "Virtual Boy" : Name.VIRTUAL_BOY,
    "Neo Geo Pocket" : Name.NEO_GEO_POCKET,
    "Neo Geo Pocket Color" : Name.NEO_GEO_POCKET_COLOR,
    "V.Smile" : Name.V_SMILE,
    "Pinball" : Name.PINBALL,
    "Arcade" : Name.ARCADE,
    "Nuon" : Name.NUON,
    "Xbox 360 Games Store" : Name.XBOX_360_GAMES_STORE,
    "Wii Shop" : Name.WII_SHOP,
    "Playstation Network Ps3" : Name.PLAYSTATION_NETWORK_PS3,
    "Leapster" : Name.LEAPSTER,
    "Microvision" : Name.MICROVISION,
    "Famicom Disk System" : Name.FAMICOM_DISK_SYSTEM,
    "Pioneer Laseractive" : Name.PIONEER_LASERACTIVE,
    "Adventure Vision" : Name.ADVENTURE_VISION,
    "Pc" : Name.PC,
    "Sharp X68000" : Name.SHARP_X68000,
    "Iphone" : Name.IPHONE,
    "Satellaview" : Name.SATELLAVIEW,
    "Arcadia 2001" : Name.ARCADIA_2001,
    "Aquarius" : Name.AQUARIUS,
    "Nintendo 64dd" : Name.NINTENDO_64DD,
    "Pippin" : Name.PIPPIN,
    "R Zone" : Name.R_ZONE,
    "Hyperscan" : Name.HYPERSCAN,
    "Game Wave" : Name.GAME_WAVE,
    "Dsiware" : Name.DSIWARE,
    "Rdi Halcyon" : Name.RDI_HALCYON,
    "Fm Towns" : Name.FM_TOWNS,
    "Nec Pc 8801" : Name.NEC_PC_8801,
    "Bbc Micro" : Name.BBC_MICRO,
    "Plato" : Name.PLATO,
    "Nec Pc 9801" : Name.NEC_PC_9801,
    "Sharp X1" : Name.SHARP_X1,
    "Fm 7" : Name.FM_7,
    "Nec Pc 6001" : Name.NEC_PC_6001,
    "Playstation Network Psp" : Name.PLAYSTATION_NETWORK_PSP,
    "Nintendo 3ds" : Name.NINTENDO_3DS,
    "Sega Pico" : Name.SEGA_PICO,
    "Supergrafx" : Name.SUPERGRAFX,
    "Bally Astrocade" : Name.BALLY_ASTROCADE,
    "Ipad" : Name.IPAD,
    "Zeebo" : Name.ZEEBO,
    "Android" : Name.ANDROID,
    "Windows Phone" : Name.WINDOWS_PHONE,
    "Acorn Archimedes" : Name.ACORN_ARCHIMEDES,
    "Casio Loopy" : Name.CASIO_LOOPY,
    "Bandai Playdia" : Name.BANDAI_PLAYDIA,
    "Sharp Mz" : Name.SHARP_MZ,
    "Playstation Vita" : Name.PLAYSTATION_VITA,
    "Rca Studio Ii" : Name.RCA_STUDIO_II,
    "Xavixport" : Name.XAVIXPORT,
    "Gamepark 32" : Name.GAMEPARK_32,
    "Pokémon Mini" : Name.POKEMON_MINI,
    "Epoch Cassette Vision" : Name.EPOCH_CASSETTE_VISION,
    "Super Cassette Vision" : Name.SUPER_CASSETTE_VISION,
    "Mega Duck" : Name.MEGA_DUCK,
    "Nintendo 3ds Eshop" : Name.NINTENDO_3DS_ESHOP,
    "Wii U" : Name.WII_U,
    "Browser" : Name.BROWSER,
    "Sega Sg 1000" : Name.SEGA_SG_1000,
    "Commodore Cdtv" : Name.COMMODORE_CDTV,
    "Playstation Network Vita" : Name.PLAYSTATION_NETWORK_VITA,
    "Leapfrog Didj" : Name.LEAPFROG_DIDJ,
    "Xbox One" : Name.XBOX_ONE,
    "Playstation 4" : Name.PLAYSTATION_4,
    "Watara Supervision" : Name.WATARA_SUPERVISION,
    "Action Max" : Name.ACTION_MAX,
    "Casio Pv 1000" : Name.CASIO_PV_1000,
    "Commodore 16" : Name.COMMODORE_16,
    "Super A Can" : Name.SUPER_A_CAN,
    "Linux" : Name.LINUX,
    "Memorex Md 2500 Vis" : Name.MEMOREX_MD_2500_VIS,
    "Ouya" : Name.OUYA,
    "Amazon Fire Tv" : Name.AMAZON_FIRE_TV,
    "New Nintendo 3ds" : Name.NEW_NINTENDO_3DS,
    "Nintendo Switch" : Name.NINTENDO_SWITCH,
    "Game Master" : Name.GAME_MASTER,
    "Apple Tv" : Name.APPLE_TV,
    "Sony Smc 777" : Name.SONY_SMC_777,
    "Sam Coupé" : Name.SAM_COUPE,
    "View Master Interactive Vision" : Name.VIEW_MASTER_INTERACTIVE_VISION,
    "Fuze Tomahawk F1" : Name.FUZE_TOMAHAWK_F1,
    "Tomy Tutor" : Name.TOMY_TUTOR,
    "Gamate" : Name.GAMATE,
    "Microbee" : Name.MICROBEE,
    "Vtech Socrates" : Name.VTECH_SOCRATES,
    "Luxor Abc80" : Name.LUXOR_ABC80,
    "Jaguar Cd" : Name.JAGUAR_CD,
    "Amazon Alexa" : Name.AMAZON_ALEXA,
    "Magic Leap One" : Name.MAGIC_LEAP_ONE,
    "Advanced Pico Beena" : Name.ADVANCED_PICO_BEENA,
    "Google Stadia" : Name.GOOGLE_STADIA,
    "The Next Gen Playstation" : Name.THE_NEXT_GEN_PLAYSTATION
});

enum Categories {VIDEOS, IMAGES, SIMILAR_GAMES, CHARACTERS}

//final categoryValues = new EnumValues({
//   "Videos" : Categories.VIDEOS,
//   "Images" : Categories.IMAGES,
//   "Similar Games" : Categories.SIMILAR_GAMES,
//   "Characters" : Categories.CHARACTERS,
//});

final Map<Categories, String> categoryValues = ({
    Categories.VIDEOS : "Videos",
    Categories.IMAGES : "Images",
    Categories.SIMILAR_GAMES : "Similar Games",
    Categories.CHARACTERS : "Characters",
});